packages:
  - Backend
  - frontend
overrides:
  deepmerge-ts: ^8.0.1
  '@nestjs/swagger>js-yaml': ^5.3.0
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
