-- Phase 4: guest, reservation, and availability integrity.

-- Add the permission globally and assign it only to the built-in ADMIN and
-- MANAGER roles. Bootstrap performs the same mapping for newly created hotels.
INSERT INTO "Permission" ("id", "key", "description")
VALUES (
  gen_random_uuid(),
  'reservation.discount',
  'Apply an audited discount to a reservation'
)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "RolePermission" ("roleId", "permissionId")
SELECT r."id", p."id"
FROM "Role" r
CROSS JOIN "Permission" p
WHERE r."isSystem" = true
  AND r."name" IN ('ADMIN', 'MANAGER')
  AND p."key" = 'reservation.discount'
ON CONFLICT DO NOTHING;

-- Booking numbers are generated by the backend and stored in one canonical
-- form so whitespace/case variants cannot bypass the hotel-scoped unique key.
UPDATE "Reservation"
SET "bookingNumber" = upper(btrim("bookingNumber"));

ALTER TABLE "Reservation"
  ADD CONSTRAINT "Reservation_booking_number_canonical"
  CHECK (
    "bookingNumber" = upper(btrim("bookingNumber"))
    AND "bookingNumber" ~ '^RSV-[0-9]{6}-[A-Z0-9]{6}$'
  ),
  ADD CONSTRAINT "Reservation_cancellation_complete"
  CHECK (
    ("status" = 'CANCELLED' AND "cancelledAt" IS NOT NULL AND coalesce(btrim("cancellationNote"), '') <> '')
    OR ("status" <> 'CANCELLED' AND "cancelledAt" IS NULL AND "cancellationNote" IS NULL)
  );

-- A reservation history actor, when present, must be a user from the same
-- hotel as the reservation. This protects audit attribution if NestJS is
-- bypassed or contains a future bug.
CREATE OR REPLACE FUNCTION enforce_reservation_history_tenant()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE reservation_hotel uuid;
DECLARE actor_hotel uuid;
BEGIN
  SELECT "hotelId" INTO reservation_hotel
  FROM "Reservation" WHERE "id" = NEW."reservationId" FOR KEY SHARE;

  IF reservation_hotel IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'reservation history requires a reservation';
  END IF;

  IF NEW."changedById" IS NOT NULL THEN
    SELECT "hotelId" INTO actor_hotel
    FROM "User" WHERE "id" = NEW."changedById" FOR KEY SHARE;
    IF actor_hotel IS NULL OR actor_hotel <> reservation_hotel THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'reservation history actor belongs to another hotel';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "ReservationHistory_same_hotel"
BEFORE INSERT OR UPDATE ON "ReservationHistory"
FOR EACH ROW EXECUTE FUNCTION enforce_reservation_history_tenant();
