"use client";

import { LoaderCircle, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { ErrorMessage } from "@/components/shared/error-message";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { PermissionSelector } from "@/components/admin/roles/permission-selector";
import { getApiError } from "@/lib/api-error";
import { updateAdminRoleSchema } from "@/schemas/admin.schema";
import { adminService } from "@/services/admin.service";
import type { AdminRole } from "@/types/admin";

export function RoleEditor({ role, permissions }: { role: AdminRole; permissions: Array<{ key: string; description: string | null }> }) {
  const router = useRouter(); const [name, setName] = useState(role.name); const [description, setDescription] = useState(role.description ?? ""); const [selected, setSelected] = useState(role.permissions.map((permission) => permission.key)); const [pending, setPending] = useState<"details" | "permissions" | "delete" | null>(null); const [error, setError] = useState<string | null>(null);
  async function saveDetails(event: React.FormEvent) { event.preventDefault(); const parsed = updateAdminRoleSchema.safeParse({ name, description: description || undefined }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Review the role details."); return; } setPending("details"); setError(null); try { await adminService.updateRole(role.id, parsed.data); router.refresh(); } catch (reason) { setError(getApiError(reason).message); } finally { setPending(null); } }
  async function savePermissions() { setPending("permissions"); setError(null); try { await adminService.setRolePermissions(role.id, selected); router.refresh(); } catch (reason) { setError(getApiError(reason).message); } finally { setPending(null); } }
  async function deactivate() { setPending("delete"); setError(null); try { await adminService.deactivateRole(role.id); router.replace("/admin/roles"); router.refresh(); } catch (reason) { setError(getApiError(reason).message); setPending(null); } }
  return <div className="space-y-5">{error ? <ErrorMessage title="Unable to update role" message={error} /> : null}<form onSubmit={saveDetails}><Card><CardHeader><CardTitle>Role details</CardTitle></CardHeader><CardContent className="grid gap-5 border-t pt-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="role-name">Role name</Label><Input id="role-name" value={name} onChange={(event) => setName(event.target.value.toUpperCase())} disabled={role.isSystem || pending !== null} maxLength={64} />{role.isSystem ? <p className="text-xs text-muted-foreground">System role names cannot be changed.</p> : null}</div><div className="space-y-2 sm:col-span-2"><Label htmlFor="role-description">Description</Label><Textarea id="role-description" value={description} onChange={(event) => setDescription(event.target.value)} disabled={pending !== null} maxLength={500} rows={3} /></div></CardContent><CardFooter className="justify-end border-t"><Button type="submit" disabled={pending !== null}>{pending === "details" ? <><LoaderCircle className="animate-spin" />Saving...</> : "Save details"}</Button></CardFooter></Card></form>
    <Card><CardHeader><CardTitle>Permissions</CardTitle><p className="text-sm text-muted-foreground">Changes affect every user assigned to this role. The ADMIN role must retain user.manage and role.manage.</p></CardHeader><CardContent className="border-t pt-6"><PermissionSelector permissions={permissions} selected={selected} onChange={setSelected} disabled={pending !== null} /></CardContent><CardFooter className="justify-end border-t"><AlertDialog><AlertDialogTrigger asChild><Button disabled={pending !== null}>Review permission changes</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Update permissions for {role.name}?</AlertDialogTitle><AlertDialogDescription>This will immediately change access for {role.userCount} assigned {role.userCount === 1 ? "user" : "users"}. Active sessions are evaluated against backend permissions on subsequent requests.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={(event) => { event.preventDefault(); void savePermissions(); }}>{pending === "permissions" ? <><LoaderCircle className="animate-spin" />Updating...</> : "Update permissions"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardFooter></Card>
    {!role.isSystem && role.isActive ? <Card className="border-destructive/25"><CardHeader><CardTitle className="text-destructive">Deactivate role</CardTitle><p className="text-sm text-muted-foreground">Only unused custom roles can be deactivated. Historical records are preserved.</p></CardHeader><CardFooter className="border-t"><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" disabled={role.userCount > 0 || pending !== null}><Trash2 />Deactivate role</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Deactivate {role.name}?</AlertDialogTitle><AlertDialogDescription>This role will no longer be available for assignment. This interface cannot restore deactivated roles because the backend exposes no restore endpoint.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={(event) => { event.preventDefault(); void deactivate(); }}>{pending === "delete" ? <><LoaderCircle className="animate-spin" />Deactivating...</> : "Deactivate role"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardFooter></Card> : null}</div>;
}
