import { CalendarDays, Languages, Mail, MapPin, Phone, ShieldCheck, StickyNote } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PaymentStatusText, ReservationStatusBadge } from "@/components/shared/reservation-status-badge";
import { formatCurrency, formatShortDate } from "@/lib/format";
import type { GuestProfile as GuestProfileType } from "@/types/guest";

export function GuestProfile({ guest }: { guest: GuestProfileType }) {
  const contacts = [{ icon: Phone, label: "Phone", value: guest.phone }, { icon: Mail, label: "Email", value: guest.email ?? "Not provided" }, { icon: MapPin, label: "Address", value: guest.address ?? "Not provided" }, { icon: Languages, label: "Language", value: guest.preferredLanguage }];
  return <div className="grid gap-5 xl:grid-cols-[340px_1fr]"><div className="space-y-5"><Card><CardHeader className="border-b"><div className="flex items-start justify-between gap-3"><div><CardTitle>{guest.name}</CardTitle><p className="mt-1 font-mono text-xs text-primary">{guest.guestCode}</p></div><Badge variant="outline">{guest.totalStays} stays</Badge></div></CardHeader><CardContent className="space-y-4">{contacts.map(({ icon: Icon, label, value }) => <div key={label} className="flex gap-3"><Icon className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden="true" /><div className="min-w-0"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-0.5 break-words text-sm font-medium">{value}</p></div></div>)}</CardContent></Card><Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" />Identity</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><div><p className="text-[11px] text-muted-foreground">Document</p><p className="mt-1 font-medium">{guest.idType}</p></div><div><p className="text-[11px] text-muted-foreground">Number</p><p className="mt-1 font-mono font-medium">{guest.idNumberMasked}</p></div><p className="col-span-2 text-[11px] leading-5 text-muted-foreground">Identity details are masked by default to protect guest privacy.</p></CardContent></Card></div><div className="space-y-5"><Card className="py-0"><CardHeader className="border-b py-4"><CardTitle className="flex items-center gap-2"><CalendarDays className="size-4 text-primary" />Stay history</CardTitle></CardHeader><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Booking</TableHead><TableHead>Stay</TableHead><TableHead>Room</TableHead><TableHead>Status</TableHead><TableHead>Payment</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{guest.stays.map((stay) => <TableRow key={stay.id}><TableCell className="font-mono text-xs text-primary">{stay.bookingId}</TableCell><TableCell className="whitespace-nowrap text-xs">{formatShortDate(stay.checkIn)} – {formatShortDate(stay.checkOut)}</TableCell><TableCell className="font-medium">{stay.roomNumber}</TableCell><TableCell><ReservationStatusBadge status={stay.status} /></TableCell><TableCell><PaymentStatusText status={stay.paymentStatus} /></TableCell><TableCell className="text-right font-medium tabular-nums">{formatCurrency(stay.total, stay.currency)}</TableCell></TableRow>)}</TableBody></Table></div></Card><Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><StickyNote className="size-4 text-primary" />Guest notes</CardTitle></CardHeader><CardContent><ul className="space-y-3">{guest.notes.map((note) => <li key={note} className="rounded-lg border bg-muted/30 px-3 py-2.5 text-sm leading-5">{note}</li>)}</ul></CardContent></Card></div></div>;
}
